name: Terraform AWS Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1 

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Import Resources
      run: | 
        terraform import aws_s3_bucket.react_site react-site-bucket
        terraform import aws_iam_role.ecs_execution_role
        terraform import aws_iam_role.ecs_task_role
        terraform import aws_s3_bucket.letter_bucket
        terraform import aws_vpc.main_vpc
        terraform import aws_ecr_repository.node_repo


    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Commit Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Update .terraform.lock.hcl"
        git push origin HEAD:main